// Code generated by MockGen. DO NOT EDIT.
// Source: tax/calculation.go

// Package tax is a generated GoMock package.
package tax

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCalculator is a mock of Calculator interface.
type MockCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCalculatorMockRecorder
}

// MockCalculatorMockRecorder is the mock recorder for MockCalculator.
type MockCalculatorMockRecorder struct {
	mock *MockCalculator
}

// NewMockCalculator creates a new mock instance.
func NewMockCalculator(ctrl *gomock.Controller) *MockCalculator {
	mock := &MockCalculator{ctrl: ctrl}
	mock.recorder = &MockCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculator) EXPECT() *MockCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockCalculator) Calculate(param CalculationRequest) CalculationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", param)
	ret0, _ := ret[0].(CalculationResult)
	return ret0
}

// Calculate indicates an expected call of Calculate.
func (mr *MockCalculatorMockRecorder) Calculate(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockCalculator)(nil).Calculate), param)
}
